### ISSUE TITLE
NaN in PTM_0_num column

### ISSUE THREAD

**Issue by fazeliniah** [AlexHgO/Perseus_Plugin_Peptide_Collapse#1]
Hi Alex, 
Thanks again for developing this very useful tool. 
I am analyzing the PhosphoDIA data with Spectronaut/Perseus using the plugin to collapse the peptides (using the linear model). Everything works beautifully however I have noticed that for small fraction of my data the "PTM_0_num" data is reported as NaN (Please see attached Excel file). When I checked, all of the corresponding peptides for this fraction of data have 3 phosho events. I am wondering what the reason is for the NaN.
[PTM_0_num_NAN_issue.xlsx](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/files/4417153/PTM_0_num_NAN_issue.xlsx)

Thanks

**Comment by AlexHgO** [comment]
Thanks for your comment! Hmm, that is weird. Would you be able to provide me with the input matrix, i.e. the one used to run the plugin on? Ideally, export the matrix directly from Perseus. I will then try to look into it this week.

**Comment by fazeliniah** [comment]
Here is the link to file...
https://www.dropbox.com/s/ai1ob0irb031qv5/before_collapse_phosDIA.txt?dl=0

**Comment by AlexHgO** [comment]
Hi again! So sorry for my delay, I really should have gotten back sooner, but life got in the way.
I had a look at the files you sent me now and I wonder if these NaN cases are created by a string to number column type conversion. Specifically, the cases you sent me all were sites created by merging peptides with different numbers of target PTMs on them, e.g. 1 peptide with 3 phosphorylations plus 1 peptide with 4 phosphorylations. These would then be reported back as "3;4" in the PTM_0_num column. If you now import this column into Excel / reimport it into Perseus as a number column, these entries will become NaN (not a number), because they report 2 numbers with a ";". I processed your data with the plugin and kept the column as a text column. In this case, all entries were properly reported as e.g. "3", "4", "5", or "3;4".
Could this explain your problem? Please tell me if this makes sense or not, I have more time now and can get back to you quicker.
Thanks and kind regards,
Alexander

**Comment by fazeliniah** [comment]
Thank you very much for your explanation. That fixed the issue.
