### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mez2005** [AlexHgO/Perseus_Plugin_Peptide_Collapse#10]
Hi Alex,
Thank you for providing such useful tool and your effort to maintain it. I am trying some DIA-phosphoprotemics workflow and using Peptide Collapse plugin for Dia-NN result files. The result files have been converted to the suitable format. I had one file that didn't work (attached). It gave an error message at the end. Could you please help me to understand what caused the problem? I had other files (in the same format) that worked out well. The only difference is the failed one only had one acquisition file (R. File name). 
Thank you so much for your attention.
Best regards,
Melinda

![ErrorMessage](https://user-images.githubusercontent.com/109565962/179801135-cc6d750b-a55a-4e80-99ab-f296f2682ae7.jpg)
![Parameters](https://user-images.githubusercontent.com/109565962/179801138-8f455698-b710-4893-9f43-2c9d11e5ef98.jpg)
[report_converted.txt](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/files/9142958/report_converted.txt)

**Comment by AlexHgO** [comment]
Hi Melinda,
Thanks for sharing your data. Yes, the plugin is not designed to work with input files that only have 1 input group or condition, as it was built to facilitate inter-conditional comparisons. There is a filtering step that kicks out all rows that have less than 1 observation per peptide, and since in this case there can only ever be max 1 observation, processing fails.
The easiest workaround here is to reanalyze the data together with other similar samples you want to compare against, and then reprocess the combined result file using the plugin. If that's not possible, you could try tricking the plugin by just copying all rows below the initial rows, but making up a fake R.File name. The plugin will then treat them as separate conditions and should run through successfully.
Hope this helps, and glad you find the plugin useful!

**Comment by mez2005** [comment]
Thanks a lot for your quick reply and explanation - it really helps!
