### ISSUE TITLE
Using the Plugin with DIA-NN outputs

### ISSUE THREAD

**Issue by dorvashmr** [AlexHgO/Perseus_Plugin_Peptide_Collapse#11]
Hi Alex,

First, thank you for the amazing you have done with this plugin.

I wanted to use your plugin for some phospho-enrichment vs total-proteomics DIA acquisitions that were searched with DIA-NN.
My question might sound a bit amateur. Which DIA-NN output should we use as the input file for the plugin and what likes of changes should be done to that output matrix so it is compatible with the Peptide Collapse?

Cheers,
Reza

**Comment by AlexHgO** [comment]
Hi Reza,
Thanks so much, I'm glad you appreciate it!

In order to achieve what you want, the plugin needs to be extended to take DIA-NN input. Since I left this postdoc in 2019 and am no longer paid by it, I do not have capacity to implement that I fear. You could try to reach out to Jesper Olsen instead, the corresponding author of the study.

Alternatively, it's also possible to take DIA-NN output and parse it's columns into Spectronaut or MaxQuant format. You could do that e.g. in R, and then feed it into the plugin as usual.

If I do find extra time I'll let you know, but please do not count on it.
I hope this helps!
Best regards,
Alex
