### ISSUE TITLE
PTM_collapse_key incomplete

### ISSUE THREAD

**Issue by hcadre** [AlexHgO/Perseus_Plugin_Peptide_Collapse#14]
Applying the Perseus Peptide_collapse plugin on a Spectronaut report (phosphopeptide-enriched samples), I noticed that for some phosphosites (green) the corresponding amino acid is neither provided in the PTM_collapse_key column nor in the PTM_0_aa - column (amino acid code substituted be a seemingly arbitrary number from 1-9)

![image](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/assets/16349515/f55c5456-65f1-42d8-b8ee-5f2911cda9fc)

This happens although the localization probability for the corresponding pS - site site is given with 100% and affects about 5% of all phosphosites

![image](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/assets/16349515/c0859e25-1de1-4b82-85df-e3caddef3bb0)

How do I have to interpret these data?

**Comment by AlexHgO** [comment]
Hi hcadre,
Please apologize my delayed response. It's difficult to say without any closer look at the data, but my guess is that either 1) the amino acid you want to collapse on is not listed at first position, or 2) the Spectronaut report contains modifications not declared in in the plug-in configuration. Please check that everything is correct. If you are still running into problems and need to have this fixed, feel free to contact me and I'll have a look at your data. 

Since it has been over 5 years now since this plug-in was published, Spectronaut changed major versions multiple times and I am not employed in academia anymore, I will retire this repository. If you can, I recommend using the built-in site and stoichiometry report of newer Spectronaut versions, since they are being actively maintained by the developers.
