### ISSUE TITLE
Question about PTM_group

### ISSUE THREAD

**Issue by fazeliniah** [AlexHgO/Perseus_Plugin_Peptide_Collapse#8]
Hi Alex, 
Hope all is fine. 
Our collaborator has come across an interesting case that I couldn't find answer to. I have attached the data in a small excel file. 
In brief, they are interested in Mapk1 kinase P63085.  We have identified a peptide with potential phosphorylation sites at T178, T183, and Y185.  The question is about the peptide with (T183, Y185) phospho sites. This peptide was once reported alone as P63085_Y185_M2. It seems that the same peptide was also grouped with another identification with T178 & T183 sites  and reported as P63085_T183_M2. As you can see, the intensity of these groups varied considerably. 
My questions: 
1- Why the same peptide happened to be counted twice?   
2- How were the collapsing residues determined for a peptide for multiple sites?   
Hope this makes sense.
Thanks
[peptidecollapse_issue.xlsx](https://github.com/AlexHgO/Perseus_Plugin_Peptide_Collapse/files/8091413/peptidecollapse_issue.xlsx)

**Comment by AlexHgO** [comment]
Hi,
Apologies for the long delay, I was swamped with a manuscript submission.
Yes, I think I understand the situation. The idea here is that a site-table should represent all peptides that can add quantitative information for that site, while at the same time keeping singly (M1), doubly (M2) and multiply (M3) phosphorylated peptides separate (as they can show differential regulation). So to address your questions:

1. The peptide "_VADPDHDHTGFLT[Phospho (STY)]EY[Phospho (STY)]VATR_.3" contains 2 phospho-sites, T183 and Y185. This peptide thus contains quantitative information for sites T183 and Y185, and will be used to quantify both. They will be marked T183_M2 and Y185_M2 because the peptide(s) it originated from contained exactly 2 phospho-sites.

2. The plugin considers all unique sites (on gene or protein level, depending what was selected), that remain after localization filtering (if selected). The rationale here is that if e.g. a peptide is significantly up-regulated, then that represents an up-regulation of both sites, so it should be counted for both. Since mono- and doubly-phosphorylated peptides often show different regulation, however, we do not merge peptides that only have 1 phospho-site with those that have 2, but rather keep them separate as M1 and M2. So in the example you attached:
_VADPDHDHTGFLTEY[Phospho (STY)]VATR_.3 - only has 1 site, and thus only counts for Y185_M1
_VADPDHDHTGFLT[Phospho (STY)]EY[Phospho (STY)]VATR_.3 has 2 sites, and is thus considered for both T183_M2 and Y185_M2
_VADPDHDHTGFLT[Phospho (STY)]EYVAT[Phospho (STY)]R_.3 has 2 sites, and is thus considered for both T183_M2 and T188_M2

I hope this makes sense! If not, please let me know.
I also saw in your data that the intensity input seems to be I assume log transformed in some way. If this log-transformation was done after using the plugin, then that's good. Otherwise please keep in mind that the plugin was designed to work with non-transformed data, as the input values are summed during calculations (e.g. three peptides with a shared site and intensities 50, 60 and 80 will yield summed intensity 190 for that site). Just to make sure everything is good there!
Hope this helps, please don't hesitate to reach out again if things are still unclear - I promise I will answer quicker this time.
Best, Alexander
