### ISSUE TITLE
Question of repeat the stoichiometry benchmark experiment 

### ISSUE THREAD

**Issue by yuz2011** [AlexHgO/Perseus_Plugin_Peptide_Collapse#9]
Hi Alex,
I hope this email finds you well.
I have encountered two problems when I try to repeat the stoichiometry benchmark experiment (Fig 4a-c) in Rapid and site-specific deep phosphoproteome profiling by data-independent acquisition without the need for spectral libraries.
1. When I use the Peptide Collapse Plugin for the data of the original paper (20190526_012717_DIA_stoichiometry_benchmark_3libs_Report_cut0d75.xls downloaded form PXD14525), it shows error. Please see the attached setting image and error image. 
2. Does different site localization influence the result? As it is a PTM peptide-level collapse, I wonder how site localization influence the result. If there is phosphopeptides with different localizations and different number of phosphosites, which one will be used for stoichiometry calculation against non-phosphorylated peptides?
Many thanks for your kind help.

Best,
Yu
![setting1](https://user-images.githubusercontent.com/106479481/178767571-46408aa3-60d8-43dc-955a-24a27bffd956.png)
![setting2](https://user-images.githubusercontent.com/106479481/178767634-011fad52-1c52-44c0-8d4c-2aa074f7d437.png)
![error](https://user-images.githubusercontent.com/106479481/178768680-c964fcd5-b18b-4072-8779-a13ce3b15814.png)

**Comment by AlexHgO** [comment]
Hi Yu,
Thanks for reaching out. I'll try to address your questions here below.
1. This was indeed a bug, caused I assume by an update of the package data.table that I am using. I updated the plugin to v1.4.4, and it should work now again. Please let me know if the problem still happens.
2. For the settings you have chosen, the plugin will extract the localization probability for each site per peptide (as found in the column EG.PTMLocalizationProbabilities), take the MAXIMUM of that, and then filter >=0.75. So for example, if a peptide has two phospho-sites with localization probabilities 0.3 and 0.8, respectively, it will not be kicked out due to 0.8>0.75. If you prefer to filter peptides differently, you can do your own filtering before running the plugin, and then set "Localization cutoff" to 0, which will skip filtering.
Hope this helps!
Best, Alex

**Comment by yuz2011** [comment]
Hi Alex,

Thanks for the help very much! It did fix the bug but the results are different. May I ask two more questions?
1. How to perform the quantile-normalization? I follow the paper and de-normalized the intensities by dividing the intensity by the EG.NormalizationFactor before stoichiometry calculation . As I see, maybe the quantile normalization should perform for the collapsed site. However, if I use the peptide collapse plugin and then directly use the quantile normalization embedded in Perseus, it yields NaN for the intensity (Fig1.png). Could you please tell me how you perform the quantile normalization?
![Fig1](https://user-images.githubusercontent.com/106479481/179358287-1e989be6-5225-4e06-a7bd-ce3fa2b415c0.png)

2. Different ways to deal with peptides of different sites. In the SI of your paper (result1.png), it only yield "occ" for one site with sum probability different from one. For the result I performed with the new plugin, "occ" is for both sites (result2.png).  The PTM_stoich_key_PTMnum is 0;1 but with two phosphopeptides. Under this circumstance, how to calculate the "occ", like summing up the "occ" for phosphopeptides or anything you think more reasonable based on the designing ideas of this plugin?
![result1](https://user-images.githubusercontent.com/106479481/179358330-af649a76-cc99-4b1c-86e2-d4ad9a5d2ae7.png)
![result2](https://user-images.githubusercontent.com/106479481/179358334-2f10dcd2-0802-4b39-b995-6ab8b92efa81.png)
It will help a lot if you could give me some support and suggestions. I appreciate it very much.
Best wishes,
Yu

**Comment by AlexHgO** [comment]
Hi Yu,

Glad that I could help you so far!
For your two new questions:

  1.  Quantile based normalization has to be performed BEFORE using the peptide collapse / stoichiometry plugin. To do so, you need to:
     a   Load your data
     b   Log-transform it (e.g. log2 or log10)
     c  Perform quantile normalization
     d   De-log-transform it (i.e. 2^x or 10^x, respectively)
     e   Perform peptide collapse / stoichiometry calculation
Step d is necessary because the peptide collapse / stoichiometry calculation plugin uses non-log-transformed input values.

  2.  Occupancy values calculated for different peptides covering the same sites represent individual assessments of those sites. E.g., peptide LSHLIT(ph)K might yield very different occupancy values for site T(ph) than LS(ph)HLIT(ph)K. If you do want site-level information, then I would suggest calculating the mean for different occupancy sites.
Hope this helps and best regards,
Alexander

**Comment by yuz2011** [comment]
Hi Alex,
Thanks for your reply!
1. Quantile normalization couldn't be applied to one column. However, the loaded file contains only one intensity column ( “EG.TotalQuantity (Settings)”).  [Quantile normalization is used to normalize the distribution of different conditions. If I directly use the quantile normalization of Perseus, it will report "at least three columns are needed".]
2. Besides, do you have the raw files for the spectral library Yeast-phospho-library-15min.kit provided in the original paper (Fig). As it belongs to the experimental section, otherwise could you please refer me to the researcher that owns the resource?
![image](https://user-images.githubusercontent.com/106479481/180006776-d52516d1-0b77-4805-9a48-9603f04726ce.png)
 Many thanks for you time and support!

Best,
Yu

**Comment by AlexHgO** [comment]
Hi Yu,
Yes I see the problem.
1. I am unfortunately not aware of a way (other than the plugin) to transform Spectronaut long-table data into the Perseus used wide-table format, which you need for quantile-based normalization. I would recommend trying to find a way to do that manually, in R (via pivot_wider), or to use the Spectronaut internal normalization method instead of quantile normalization.
2. I don't have access to these raw files unfortunately. I'd recommend contacting Jesper Olsen and Dorte-Bekker Jensen and inform them, that they are not part of the original Pride upload.
Best,
Alexander

**Comment by yuz2011** [comment]
Hi Alex,
Many thanks for your advice and support! It did help me solve many problems.

Best,
Yu
